version: '3'

tasks:
  # watch:
  #   desc: "Wails dev"
  #   cmds:
  #     - wails dev
  pull-metamajin:
    desc: "pull new version of Meta Majin"
    cmds:
      - go get -u github.com/yasha-gh/meta-majin
  tag:
      desc: Create and push a new tag
      cmds:
        - |
          if git diff-index --quiet HEAD --; then
            git fetch origin master
            git tag -fa "latest" -m "latest"
            git push origin tag "latest"
          else
            echo "Error: There are uncommitted changes. Please commit or stash your changes before creating a new tag."
            exit 1
          fi
